language: node_js

notifications:
  irc:
    channels:
      - "irc.freenode.org#cssnext"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true


before_script:
  # gh-pages: because of how gulp-gh-pages works (with a clone), --global is required
  - git config --global user.name "Travis-CI"
  - git config --global user.email "travis@travis-ci.org"

script:
  - npm run travis

env:
  global:
    - secure: pj+iHgVj/WLvzyz1GK6ntBNijIxm1G46Wq+tkW6RZMHXRM/mwUZCPgkQnqzcgEdjpZ9qb13OzTZuqDGseteiONupNM46tMU6u18XrUKYsoxe5mHr/P3LsCrlOZDeNam3FBbgG6q/SBoMkTtuwijsoEE/G1MjOYjF60M1cSmWeHI=
